const char area[30][32] = {
  {"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},
  {"X                              X"},
  {"X                X          X  X"},
  {"X                X XX  XX XXXX X"},
  {"X     XXXXX      X             X"},
  {"X          X     X   X      X  X"},
  {"X X         XXX  XX   XXXXX    X"},
  {"X  X          XXXXXXXXXXXXX    X"},
  {"X   X                          X"},
  {"X              X               X"},
  {"X           XXX X  X           X"},
  {"X XX                      XXXX X"},
  {"X         X          X   X     X"},
  {"X       X    X   X    XXXX     X"},
  {"X  XX XXXX          X          X"},
  {"X       X                      X"},
  {"X        X     XXXX   X XXX    X"},
  {"X     X      X        X XX     X"},
  {"X         XX         XX  X     X"},
  {"X XXXXXXXXXXXXXXXXXXXXXXXXXX   X"},
  {"X                              X"},
  {"X   XXXXXXXXXXXXXXXXXXXXXXXXXX X"},
  {"X                              X"},
  {"X                 X     XXX    X"},
  {"X X              X X    X X    X"},
  {"X   X      XXXX   X     XXX    X"},
  {"X   X   X                      X"},
  {"X                              X"},
  {"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}
};
